# use local env.config.yml for your specific configuration
# i.e.: Steam API key

server:
  port: 1337
  context: /

static:
  protocol: ''
  host: ''
  context: /static

lowdb:
  games: './data/games.cache.json'

log:
  # error
  # warn
  # info
  # http
  # verbose
  # debug
  # silly
  level: error
  override:
    # initial server start
    server: info
    # express server lifecycle
    express: http
#    steamspy: debug
#    steam: info

steamspy:
  requestInterval: 300
  multiplayerTags:
    - Multiplayer
    - PvP
    - Online Co-Op
    - Massively Multiplayer

steam:
  apiKey: null
